# Generated by Django 4.0.6 on 2022-08-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
