# Generated by Django 4.0.6 on 2022-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0005_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
