# Generated by Django 4.0.6 on 2022-08-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Guest', 'Guest Member'), ('Valid', 'Valid Member')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('current_address', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone_home', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Other', 'Other')], max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('+AB', 'AB POSITIVE'), ('-AB', 'AB NEGATIVE'), ('+O', 'O POSITIVE'), ('-O', 'O NEGATIVE'), ('+B', 'B POSITIVE'), ('-B', 'B NEGATIVE'), ('+A', 'A POSITIVE'), ('-A', 'A NEGATIVE')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('gym_experience', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=150, null=True)),
                ('refered_by', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Friends', 'Friends'), ('Others', 'Others')], max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_charge', models.FloatField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('local_gov', models.CharField(blank=True, max_length=100)),
                ('ward_no', models.IntegerField(blank=True, null=True)),
                ('street_or_tole', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('citizen_or_passport_num', models.CharField(blank=True, max_length=200)),
                ('medical_problems', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_address', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, help_text='Kgs')),
                ('neck', models.FloatField(blank=True, help_text='inches')),
                ('chest', models.FloatField(blank=True, help_text='inches')),
                ('fore_arms', models.FloatField(blank=True, help_text='inches')),
                ('arms', models.FloatField(blank=True, help_text='inches')),
                ('hip', models.FloatField(blank=True, help_text='inches')),
                ('waist', models.FloatField(blank=True, help_text='inches')),
                ('thigh', models.FloatField(blank=True, help_text='inches')),
                ('shoulder', models.FloatField(blank=True, help_text='inches')),
                ('calves', models.FloatField(blank=True, help_text='inches')),
                ('height', models.FloatField(blank=True, help_text='foot')),
                ('status', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_details', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('Basic(Gym & Cardio)', 'Basic(Gym & Cardio)'), ('Zumba(with Gym & Cardio)', 'Zumba(with Gym & Cardio)'), ('Zumba', 'Zumba')], max_length=50)),
                ('package_period', models.CharField(choices=[('Per Day', 'Per Day'), ('Per Week', 'Per Week'), ('Per Month', 'Per Month'), ('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year')], max_length=20)),
                ('convenient_time', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('start_date', models.DateField()),
                ('total_fee', models.FloatField(blank=True, help_text='In Rupees')),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('FonePay', 'FonePay')], max_length=50)),
                ('received_amount', models.FloatField(blank=True, default=0, help_text='In Rupees', null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_details', to='members.member')),
            ],
        ),
    ]
