# Generated by Django 4.0.6 on 2022-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='package_type',
            field=models.CharField(choices=[('Basic', 'Basic(Gym & Cardio)'), ('Zumba(with Gym & Cardio)', 'Zumba(with Gym & Cardio)'), ('Zumba', 'Zumba')], max_length=50),
        ),
    ]
