# Generated by Django 4.0.5 on 2022-07-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetails',
            name='expired',
        ),
    ]
