# Generated by Django 4.0.6 on 2022-07-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_packagedetails_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('Guest', 'Guest Member'), ('Valid', 'Valid Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='package_type',
            field=models.CharField(choices=[('Basic(Gym & Cardio)', 'Basic(Gym & Cardio)'), ('Zumba(with Gym & Cardio)', 'Zumba(with Gym & Cardio)'), ('Zumba', 'Zumba')], max_length=50),
        ),
    ]
