# Generated by Django 4.0.6 on 2022-08-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_country_alter_member_current_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetails',
            name='total_fee',
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='package_fee',
            field=models.FloatField(default=0, help_text='In Rupees'),
        ),
    ]
