# Generated by Django 4.0.6 on 2022-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
