# Generated by Django 4.0.5 on 2022-07-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_packagedetails_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_details', to='members.member'),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_details', to='members.member'),
        ),
    ]
