# Generated by Django 4.0.6 on 2022-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_packagedetails_total_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admission_charge',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
