# Generated by Django 4.0.6 on 2022-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_packagedetails_convenient_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='package_period',
            field=models.CharField(choices=[('Per Day', 'Per Day'), ('Per Week', 'Per Week'), ('Per Month', 'Per Month'), ('1 month', '1 Month'), ('3 months', '3 Months'), ('6 months', '6 Months'), ('1 year', '1 Year')], max_length=20),
        ),
    ]
