# Generated by Django 4.0.6 on 2022-08-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_admission_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicaldetail',
            name='status',
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='arms',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='calves',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='chest',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='fore_arms',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='height',
            field=models.FloatField(blank=True, help_text='foot', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='hip',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='neck',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='shoulder',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='thigh',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='waist',
            field=models.FloatField(blank=True, help_text='inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicaldetail',
            name='weight',
            field=models.FloatField(blank=True, help_text='Kgs', null=True),
        ),
    ]
